# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: PEFS - Private Encrypted File System
email: contact@pefs.io
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pefs.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll
permalink: "/:categories/:year/:month/:title/"
paginate: 12
paginate_path: "/blog/page:num/"
gems: [jekyll-paginate]
markdown: kramdown
collections:
  - root
defaults:
  -
    scope:
      path: ""
    values:
      splash_title: "PEFS"
      splash_subtitle: "Private Encrypted File System"
  -
    scope:
      path: "blog"
      type: "posts"
    values:
      layout: post
      content_headers:
        - "splash.html"
      splash_title: "PEFS Blog"
      splash_subtitle: "Latest news on the project development"
  -
    scope:
      path: "blog"
    values:
      splash_title: "PEFS Blog"
      splash_subtitle: "Latest news on the project development"
